version: '2'
services:
    mt-app:
        image: mt
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mt-postgresql:5432/mt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mt-postgresql:
        extends:
            file: postgresql.yml
            service: mt-postgresql
